import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { NextThemeProvider } from "./provider";
import { ThemeProvider } from "@mui/material/styles";
import { SidebarProvider } from "./context/SidebarContext";
import { TooltipProvider } from "@/components/ui/tooltip";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import theme from "./theme";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={outfit.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            {" "}
            <NextThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <TooltipProvider>
                <SidebarProvider>{children}</SidebarProvider>
              </TooltipProvider>
            </NextThemeProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
